name: üèÅ Windows Builds
on: [push, pull_request]

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  BRANCH_NAME: main
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=release_debug, tools=yes)
            os: windows-latest
            cache-name: windows-editor
            target: release_debug
            tools: true
            bin: "./bin/rebel.windows.opt.tools.64.exe"

          - name: Template (target=release, tools=no)
            os: windows-latest
            cache-name: windows-template
            target: release
            tools: false

          - name: MinGW GCC 8.1.0
            os: windows-2019
            build-options: use_mingw=yes
            cache-name: windows-mingw-8
            target: debug
            tools: true

          - name: MinGW GCC 14.2.0
            os: windows-2022
            build-options: use_mingw=yes
            cache-name: windows-mingw-14
            target: debug
            tools: true

          - name: MinGW GCC 15.2.0
            os: windows-2025
            build-options: use_mingw=yes
            cache-name: windows-mingw-15
            target: debug
            tools: true

    steps:
      - uses: actions/checkout@v6

      - name: Setup build cache
        uses: ./.github/actions/build-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup build dependencies
        uses: ./.github/actions/build-dependencies

      - name: Build
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.build-options }}
          platform: windows
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          scons-cache-limit: 3072

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}
